services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: perfectfit
      POSTGRES_USER: perfectfit
      POSTGRES_PASSWORD: perfectfit
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
